config_version = 14
theconfig_version = 12

[backdrop]
blur_intensity = 0.19999999552965164
enabled = true
tint_intensity = 0.0

[bar.default]
background_opacity = 0.74999998323619366
border = "primary"
border_width = 1.0
capsule = true
capsule_fill = "on_secondary"
capsule_opacity = 0.0
capsule_padding = 8.0
capsule_radius = 6
capsule_thickness = 0.74999998696148396
center = [ "clock", "workspaces" ]
end = [ "audio_visualizer", "media", "tray", "group:g6", "group:g1", "group:g5", "keybinds" ]
font_family = "Fira Sans"
margin_edge = 0
margin_ends = 8
padding = 16
panel_overlap = 0
radius = 80
radius_top_left = 0
radius_top_right = 0
shadow = false
start = [ "launcher", "group:g7", "cat", "group:g2", "group:g3", "cat_2", "weather" ]
thickness = 32

    [bar.default.dead_zone.actions]
    left = "exec noctalia msg panel-toggle control-center"
    scroll_down = "exec noctalia msg volume-down 2"
    scroll_up = "exec noctalia msg volume-up 2"

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "on_secondary"
    id = "g2"
    members = [ "temp", "ram" ]
    opacity = 0.0
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = false
    fill = "on_secondary"
    id = "g3"
    members = [ "network_rx", "network_tx" ]
    opacity = 0.34999999403953552
    padding = 6.0
    radius = 6.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "on_secondary"
    id = "g1"
    members = [ "network", "volume", "battery", "brightness", "bluetooth" ]
    opacity = 0.0
    padding = 8.0
    radius = 6.0
    widget_spacing = 4

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "on_secondary"
    id = "g5"
    members = [ "session", "control-center" ]
    opacity = 0.0
    padding = 8.0
    radius = 6.0

    [[bar.default.capsule_group]]
    accordion = true
    accordion_direction = "start"
    enabled = true
    fill = "on_secondary"
    id = "g6"
    members = [ "notifications", "widget", "recorder", "clipboard" ]
    opacity = 0.0
    padding = 8.0
    radius = 6.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "on_secondary"
    id = "g7"
    members = [ "wallhaven", "wallpaper" ]
    opacity = 0.0
    padding = 8.0
    radius = 6.0

[control_center]
sidebar = "full"
sidebar_section = "full"
width = 1020

[desktop_widgets]
schema_version = 2
widget_order = [
    "desktop-widget-0000000000000001",
    "desktop-widget-0000000000000002",
    "desktop-widget-0000000000000003",
    "desktop-widget-0000000000000004"
]

    [desktop_widgets.grid]
    cell_size = 8
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 336.0
    box_width = 1792.0
    cx = 872.4998779296875
    cy = 818.9998779296875
    output = "eDP-1"
    placement_height = 982.0
    placement_width = 1745.0
    rotation = 0.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background = false
        bands = 128
        centered = false
        mirrored = false
        show_when_idle = false

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 408.0
    box_width = 1936.0
    cx = 944.0
    cy = 879.99993896484375
    output = "DP-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        background = false
        bands = 128
        centered = false
        mirrored = false
        show_when_idle = false

    [desktop_widgets.widget.desktop-widget-0000000000000003]
    box_height = 80.0
    box_width = 424.0
    cx = 244.5
    cy = 195.0
    enabled = false
    output = "eDP-1"
    placement_height = 982.0
    placement_width = 1745.0
    rotation = 0.0
    type = "yocraft/desktop-launcher:widget"

        [desktop_widgets.widget.desktop-widget-0000000000000003.settings]
        apps = [ "kitty", "brave-browser", "code", "slack", "firefox" ]
        background = false
        columns = 8
        grid_layout = true

    [desktop_widgets.widget.desktop-widget-0000000000000004]
    box_height = 80.0
    box_width = 424.0
    cx = 248.0
    cy = 196.0
    output = "DP-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "yocraft/desktop-launcher:widget"

        [desktop_widgets.widget.desktop-widget-0000000000000004.settings]
        apps = [ "kitty", "brave-browser", "code", "slack", "firefox" ]
        background = false
        columns = 8
        grid_layout = true

[dock]
active_monitor_only = true
auto_hide = true
enabled = false
launcher_position = "start"
reserve_space = false

[hot_corners]
enabled = true

    [hot_corners.top_right]
    action = "control_center"

[location]
address = "Lagankhel"
auto_locate = false

[lockscreen]
allow_empty_password = true
fingerprint = false
transition = [ "disc", "honeycomb", "stripes", "wipe" ]
transition_duration = 1100

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@DP-2",
    "lockscreen-login-box@HDMI-A-1",
    "lockscreen-login-box@eDP-1",
    "lockscreen-widget-000000000000000f",
    "lockscreen-widget-0000000000000014",
    "lockscreen-widget-0000000000000015",
    "lockscreen-widget-0000000000000016",
    "lockscreen-widget-0000000000000017",
    "lockscreen-widget-0000000000000018",
    "lockscreen-widget-0000000000000019",
    "lockscreen-widget-000000000000001a",
    "lockscreen-widget-000000000000001b",
    "lockscreen-widget-000000000000001c",
    "lockscreen-widget-000000000000001d"
]

    [lockscreen_widgets.grid]
    cell_size = 8
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
    box_height = 196.0
    box_width = 720.0
    cx = 911.9998779296875
    cy = 870.0
    output = "DP-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 928.0
    cx = 752.0
    cy = 726.0
    output = "HDMI-A-1"
    placement_height = 864.0
    placement_width = 1536.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 880.5
    cy = 861.0
    output = "eDP-1"
    placement_height = 982.0
    placement_width = 1745.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-000000000000000f]
    box_height = 32.0
    box_width = 96.0
    cx = 1780.000244140625
    cy = 319.20004272460938
    output = "HDMI-A-1"
    placement_height = 864.0
    placement_width = 1536.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-000000000000000f.settings]
        background = false
        background_opacity = 0.0
        background_padding = 0
        background_radius = 0
        center_text = false
        clock_style = "digital"
        font_family = ""
        format = "{:%H:%M:%S}"
        shadow = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000014]
    box_height = 184.0
    box_width = 928.0
    cx = 752.0
    cy = 484.0
    output = "HDMI-A-1"
    placement_height = 864.0
    placement_width = 1536.0
    rotation = 0.0
    type = "audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000014.settings]
        background = false
        background_opacity = 0.0
        background_radius = 0
        bands = 72
        centered = false
        mirrored = false
        show_when_idle = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000015]
    box_height = 80.0
    box_width = 176.0
    cx = 1805.5999755859375
    cy = 876.0001220703125
    output = "HDMI-A-1"
    placement_height = 864.0
    placement_width = 1536.0
    rotation = 0.0
    type = "weather"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000015.settings]
        background = false
        background_opacity = 0.0
        background_radius = 0
        forecast_days = 6
        shadow = true
        show_forecast = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000016]
    box_height = 48.0
    box_width = 176.0
    cx = 564.0
    cy = 1151.1998291015625
    output = "HDMI-A-1"
    placement_height = 864.0
    placement_width = 1536.0
    rotation = 0.0
    type = "button"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000016.settings]
        background = true
        color = "primary"
        command = "noctalia msg session logout"
        glyph = "logout"
        hover_background = "secondary"
        label = "Logout"
        variant = "outline"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000017]
    box_height = 48.0
    box_width = 192.0
    cx = 1172.0
    cy = 1151.1998291015625
    output = "HDMI-A-1"
    placement_height = 864.0
    placement_width = 1536.0
    rotation = 0.0
    type = "button"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000017.settings]
        background = true
        color = "primary"
        command = "noctalia msg session reboot"
        glyph = "reboot"
        hover_background = "secondary"
        label = "Reboot"
        variant = "outline"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000018]
    box_height = 48.0
    box_width = 192.0
    cx = 1786.4000244140625
    cy = 1151.1998291015625
    output = "HDMI-A-1"
    placement_height = 864.0
    placement_width = 1536.0
    rotation = 0.0
    type = "button"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000018.settings]
        background = true
        color = "error"
        command = "noctalia msg session shutdown"
        glyph = "shutdown"
        hover_background = "error"
        label = "Shutdown"
        variant = "outline"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000019]
    box_height = 376.0
    box_width = 536.0
    cx = 880.5
    cy = 347.0
    output = "eDP-1"
    placement_height = 982.0
    placement_width = 1745.0
    rotation = 0.0
    type = "label"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000019.settings]
        title = ""

    [lockscreen_widgets.widget.lockscreen-widget-000000000000001a]
    box_height = 144.0
    box_width = 392.0
    cx = 880.5
    cy = 227.0
    output = "eDP-1"
    placement_height = 982.0
    placement_width = 1745.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-000000000000001a.settings]
        background = false
        format = "{:%H:%M:%S}"

    [lockscreen_widgets.widget.lockscreen-widget-000000000000001b]
    box_height = 24.0
    box_width = 528.0
    cx = 880.5
    cy = 283.0
    output = "eDP-1"
    placement_height = 982.0
    placement_width = 1745.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-000000000000001b.settings]
        background = false
        format = "{:%a, %b %d}"

    [lockscreen_widgets.widget.lockscreen-widget-000000000000001c]
    box_height = 200.0
    box_width = 864.0
    cx = 872.5
    cy = 615.0
    output = "eDP-1"
    placement_height = 982.0
    placement_width = 1745.0
    rotation = 0.0
    type = "audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-000000000000001c.settings]
        background = false
        bands = 64
        centered = false
        mirrored = false
        show_when_idle = true

    [lockscreen_widgets.widget.lockscreen-widget-000000000000001d]
    box_height = 160.0
    box_width = 472.0
    cx = 876.5
    cy = 427.0
    output = "eDP-1"
    placement_height = 982.0
    placement_width = 1745.0
    rotation = 0.0
    type = "sysmon"

        [lockscreen_widgets.widget.lockscreen-widget-000000000000001d.settings]
        background = true
        background_color = "surface_variant"
        background_opacity = 1.0
        background_padding = 8
        display = "graph"
        stat = "cpu_usage"
        stat2 = "cpu_temp"

[nightlight]
enabled = true
temperature_day = 5000
temperature_night = 2000

[osd]
position = "bottom_center"

[plugin_settings."noctalia/screen_recorder"]
audio_source = "none"
video_encoder = "cpu"

[plugins]
enabled = [
    "noctalia/bongocat",
    "noctalia/wallhaven",
    "oldirtty/color_picker",
    "dotnetrob/cat",
    "apex077/eyecare",
    "yocraft/desktop-launcher",
    "noctalia/screen_recorder"
]

[shell]
font_family = "IBM Plex Sans"
niri_overview_type_to_launch_enabled = true
password_style = "random"
polkit_agent = true
settings_show_advanced = true
telemetry_enabled = true

    [shell.animation]
    speed = 0.5000000074505806

    [shell.launcher]
    app_grid = true
    compact = true

    [shell.panel]
    borders = true
    clipboard_placement = "attached"
    launcher_placement = "attached"
    open_near_click_control_center = true
    open_near_click_session = true
    session_placement = "attached"
    session_position = "center"
    shadow = true
    transparency_mode = "glass"

    [shell.session]
    grid_columns = 2

        [[shell.session.actions]]
        action = "lock"
        countdown_seconds = 10.0
        enabled = true
        shortcut = "1"
        variant = "default"

        [[shell.session.actions]]
        action = "reboot"
        countdown_seconds = 10.0
        enabled = true
        shortcut = "2"
        variant = "default"

        [[shell.session.actions]]
        action = "logout"
        countdown_seconds = 10.0
        enabled = true
        shortcut = "3"
        variant = "default"

        [[shell.session.actions]]
        action = "shutdown"
        countdown_seconds = 10.0
        enabled = true
        shortcut = "4"
        variant = "destructive"

    [shell.shadow]
    alpha = 0.58999998681247234
    direction = "center"

[theme]
builtin = "Ayu"
community_palette = "Catppuccin Macchiato Blue"
mode = "dark"
source = "community"

[wallpaper]
directory = "/home/abhinavtuladhar/Pictures/Wallpapers"
per_monitor_directories = true
transition = [ "disc", "fade", "stripes", "wipe", "zoom" ]
transition_duration = 2000

    [wallpaper.automation]
    enabled = true
    interval_seconds = 60

    [wallpaper.default]
    path = "/home/abhinavtuladhar/Pictures/Wallpapers/Trails-in-the-Sky-2nd-Chapter-Artwork-001.webp"

    [wallpaper.last]
    path = "/home/abhinavtuladhar/Pictures/Wallpapers/wp11541537-the-legend-of-heroes-trails-from-zero-wallpapers.jpg"

    [wallpaper.monitor.DP-2]
    directory = "/home/abhinavtuladhar/Pictures/Wallpapers"

    [wallpaper.monitor.eDP-1]
    directory = "/home/abhinavtuladhar/Pictures/Wallpapers"

    [wallpaper.monitors.DP-2]
    path = "/home/abhinavtuladhar/Pictures/Wallpapers/wp11541537-the-legend-of-heroes-trails-from-zero-wallpapers.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/abhinavtuladhar/Pictures/Wallpapers/Wallpaper new.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/abhinavtuladhar/Pictures/Wallpapers/Screenshot (19).png"

[widget.audio_visualizer]
bands = 64
capsule = true
capsule_padding = 4
centered = false
mirrored = false
width = 64

[widget.battery]
hide_when_full = true

[widget.brightness]
show_label = false

[widget.cat]
audio_spectrum = true
capsule = true
capsule_padding = 4
color = "primary"
font_family = "Adwaita Mono"
input_devices = [ "/dev/input/by-id/*-event-*" ]
scale = 2.0
tappy_mode = true
type = "noctalia/bongocat:cat"

[widget.cat_2]
capsule_padding = 0
cat_color = "primary"
cat_color_mode = "custom"
cat_size = 32
font_family = "JetBrains Mono"
run_threshold = 50
scale = 1.1000000000000001
show_cpu_percent = true
type = "dotnetrob/cat:cat"

[widget.clock]
font_family = "CaskaydiaCove NF"
format = "{:%Y-%m-%d %A, %-I:%M:%S %p}"

[widget.keybinds]
type = "kenn/keybind-cheatsheet:keybinds"

[widget.launcher]
custom_image = "/usr/share/icons/cachyos.svg"

[widget.media]
capsule = true
capsule_padding = 10
font_family = "JetBrains Mono"
hide_album_art = true
hide_artist = true
hide_when_no_media = true
show_progress = true
title_scroll = "always"

[widget.network]
show_label = false

[widget.network_rx]
display = "text"
font_family = "Hack Nerd Font Mono"
label_min_width = 48

[widget.network_tx]
display = "text"
font_family = "Hack Nerd Font Mono"
label_min_width = 48

[widget.ram]
display = "text"
font_family = "Iosevka NF"
highlight_color = "tertiary"
label_min_width = 64
scale = 0.90000000000000002
visualization = "none"

[widget.recorder]
type = "noctalia/screen_recorder:recorder"

[widget.session]
glyph = "pokeball"

[widget.temp]
display = "text"
font_family = "Iosevka NF"
highlight_color = "primary"
scale = 0.90000000000000002
visualization = "none"

[widget.volume]
show_label = false

    [widget.volume.actions]
    scroll_down = "volume-down 2%"
    scroll_up = "volume-up 2%"

[widget.wallhaven]
type = "noctalia/wallhaven:wallhaven"

[widget.weather]
color = "tertiary"
enabled = false
font_family = "Iosevka Nerd Font"
icon_color = "tertiary"

[widget.widget]
type = "oldirtty/color_picker:widget"

[widget.workspaces]
active_pill_size = 2.5
focused_output_only = true
hide_when_empty = true
labels_only_when_occupied = true
pill_scale = 0.80000000000000004